### ISSUE TITLE
lerna bootstrap errors out compiling opr-core

### ISSUE THREAD

**Issue by cromulus** [google/open-product-recovery#29]
## Expected Behavior
`npx lerna bootstrap` would enable me to run `npx lerna run test` with passing tests

## Actual Behavior

Looks like it is throwing an error compiling opr-core
```
> opr-core@0.5.3 prepare /Users/bill/Dropbox/0.HK/code/open-product-recovery/opr-core
> npm run compile

lerna ERR! lifecycle "prepare" errored in "opr-core", exiting 2
```

## Steps to Reproduce the Problem
1. Clone the repo
2. run `npx lerna bootstrap`
3. see the error

## Specifications
git commit: 9e3b83255bbbccfab4c0d40ded2433c10973d9c2
- Version: npx: 8.12.1, node: v18.4.0, npm: 8.12.1
- Platform: M1 MacOS 16

**Comment by johndayrichter** [comment]
Thanks for the bug report! There are two small issues that are causing this:

1. We're missing a type binding dependency in opr-core.
2. The README omits the required --hoist flag for local development.

With the hoist flag, opr-core gets the latest yargs type bindings from another dependency (in opr-example-server-gcp), so the build works. Without the hoist flag, opr-core was getting the type bindings from an older yargs version via a transitive dependency.

We're on the case.
