### ISSUE TITLE
Resolve docker build issue with opr-example-server

### ISSUE THREAD

**Issue by rvenables** [google/open-product-recovery#35]
## Expected Behavior
Running `docker build -f Dockerfile.dev -t example-opr .` from the [latest related readme](https://github.com/google/open-product-recovery/commit/07766b354ce7b55e245d5849d4aa16f41dcf1b99?short_path=bacea92#diff-bacea9233b78c7b5b4dde40f4339e0fc0eb9131234398ad011ae104699077a70) results in a successful docker image build.

## Actual Behavior
The docker build fails:

> ...
> [7/7] RUN npm build:
> **#11 0.304 Unknown command: "build"**
> #11 0.304 
> #11 0.304 Did you mean this?
> #11 0.304     npm run build # run the "build" package script
> ...

## Steps to Reproduce the Problem

1. Change to the _opr-example-server_ directory (`cd opr-example-server`)
2. Run the docker image build (`docker build -f Dockerfile.dev -t example-opr .`)

## Specifications

- Repository Version: [ad38374](https://github.com/google/open-product-recovery/commit/ad38374cc02b9af03e9dab731489a0116b0a7083)
- Platform: macOS Monterey on MacBook Air (m2)
- Docker Source Image Version: Latest (Implicit), a7434a1bf94a
- Node Version (Inside Docker Container): v19.0.0 (`docker run -it --rm node /bin/bash -c 'node --version'`)
- Docker (Client) Version Details:

Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.13.0 (89412)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by rvenables** [comment]
I think this is a simple typo and it builds and later appears to run correctly with the (seemingly correct) `RUN npm run build` alternative. 

Any objections to me opening a small PR for that adjustment?

On a related note, it might be interesting to explore automated builds of the docker image at some point.

**Comment by johndayrichter** [comment]
Hi, Rob. Please do send us a PR for that fix!

I suggest that you fix the broken build and, if you're willing, replace the no-op "test" script in opr-example-server/package.json with a script that runs the docker build. That way we'll fail our Github presubmit checks if we accidentally break the Dockerfile in the future.

I think I'd prefer not to pin the source image to a particular version. If you add the test rule I suggested above and we build the source image from head, this Dockerfile could help us detect any docker-specific problems we might introduce with future source changes.

**Comment by rvenables** [comment]
Good thinking. I'll open a combined pull request for those changes a bit later today.
